#!/usr/bin/env bash

###############################
###   test scenario
###############################
global_scenario_name=scenario_minimum_conf
source $TEST_TOOL_HOME/lib/framework.func

sc_backup_spark_conf

# basic setting
sc_update_to_spark_env "JAVA_HOME" "$JAVA_HOME"
sc_update_to_spark_default "spark.master" "spark://$SYM_MASTER_HOST:7077"

# change log level to ERROR
#ca_update_to_spark_log4j "log4j.rootCategory" "ERROR"
ca_update_to_spark_log4j "log4j.appender.console.layout.ConversionPattern" "%r %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n"


