#!/bin/bash

#source env
source ./conf/environment.conf
source ./lib/framework.func
source ./lib/worklaod.func

#run scenario
source ./scenario/scenario_fifo_conf 

#case name
#val_case_name=submition-client-akka

#run case
echo "$val_case_name - begin" 
echo "$val_case_name - sbumit job"
$SPARK_HOME/bin/spark-submit --conf spark.master=ego-client --class job.submit.control.submitSleepTasks $SAMPLE_JAR 3 6000 &>> $val_case_log_dir/tmpOut &
sleep 25
lineOutput=`ca_find_by_key_word $val_case_log_dir/tmpOut "Job done"|wc -l`
#echo "$val_case_name - job output: $joboutput" #fortest
echo "$val_case_name - write report"

#create case result
ca_assert_num_ge $lineOutput 1 "job not done."
echo "$val_case_name - end" 

ca_recover_and_exit 0;
